name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: pytest

    - name: SonarQube Scan
      run: sonar-scanner \
  -Dsonar.projectKey=githubdeneme \
  -Dsonar.sources=. \
  -Dsonar.host.url=http://localhost:9000 \
  -Dsonar.token=sqp_048bc89bc6a42db0a6e3638b5d9b8c6d0e894b52
  
    - name: Deploy with Ansible
      run: ansible-playbook deploy.yml
