
- name: Copy project files
  hosts: localhost
  become: yes
  tasks:
    - name: Copy project files
      ansible.builtin.copy:
        src: /mnt/c/Users/hp/desktop/pydeneme/dnmklsr
        dest: /var/www/dnmklsr/
      notify: Restart Service

- name: Restart Service
  hosts: localhost
  become: yes
  tasks:
    - name: Restart your service
      systemd:
        name: deneme.py.py
        state: restarted
